- name: ACS med Kubernetes
  href: ./index.yml
- name: Översikt
  items:
    - name: Om Container Service
      href: container-service-intro-kubernetes.md
- name: Snabbstarter
  expanded: true
  items:
    - name: Kubernetes – Linux
      href: container-service-kubernetes-walkthrough.md
- name: Självstudier
  items:
    - name: 1 – Skapa behållaravbildningar
      href: container-service-tutorial-kubernetes-prepare-app.md
    - name: 2 – Skapa behållarregister
      href: container-service-tutorial-kubernetes-prepare-acr.md
    - name: 3 – Skapa Kubernetes-kluster
      href: container-service-tutorial-kubernetes-deploy-cluster.md
    - name: 4 – Köra program
      href: container-service-tutorial-kubernetes-deploy-application.md
    - name: 5 – Skala program
      href: container-service-tutorial-kubernetes-scale.md
    - name: 6 – Uppdatera program
      href: container-service-tutorial-kubernetes-app-update.md
    - name: 7 – Övervaka med OMS
      href: container-service-tutorial-kubernetes-monitor.md
- name: Exempel
  items:
    - name: Azure CLI
      href: cli-samples.md
- name: Koncept
  items:
    - name: Säkra behållare
      href: container-service-security.md
    - name: Tjänstens huvudnamn – Kubernetes
      href: container-service-kubernetes-service-principal.md
- name: Instruktionsguider
  items:
    - name: Kubernetes med Windows
      href: container-service-kubernetes-windows-walkthrough.md
    - name: Kubernetes-webbgränssnitt
      href: container-service-kubernetes-ui.md
    - name: Distribuera Helm-diagram
      href: container-service-kubernetes-helm.md
    - name: Jenkins och ACS Kubernetes
      href: container-service-kubernetes-jenkins.md
    - name: Använd utkast med ACR och ACS
      href: container-service-draft-up.md
    - name: Anslut med ett ACS-kluster
      href: container-service-connect.md
    - name: Skala ett ACS-kluster
      href: container-service-scale.md
    - name: Belastningsutjämna ett Kubernetes ACS-kluster
      href: container-service-kubernetes-load-balancing.md
    - name: Övervaka
      items:
        - name: Övervaka med OMS
          href: container-service-kubernetes-oms.md
        - name: Övervaka med Datadog
          href: container-service-kubernetes-datadog.md
        - name: Övervaka med Sysdig
          href: container-service-kubernetes-sysdig.md
        - name: Övervaka med CoScale
          href: container-service-kubernetes-coscale.md
    - name: Distribuera Spring Boot-appar
      items:
        - name: Distribuera ett Spring Boot-program på Linux i Azure Container Service
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Distribuera ett Spring Boot-program på ett Kubernetes-kluster i Azure Container Service
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
- name: Referens
  items:
    - name: Azure CLI 2.0
      href: /cli/azure/acs
    - name: REST
      href: /rest/api/container-services
    - name: PowerShell
      href: '/powershell/module/azurerm.compute/#container_service'
- name: Resurser
  items:
    - name: Azure-översikt
      href: 'https://azure.microsoft.com/roadmap/'
    - name: VANLIGA FRÅGOR OCH SVAR
      href: container-service-faq.md
    - name: Mallar – ACS-motor
      href: 'https://github.com/Azure/acs-engine'
    - name: Priser
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: Regional tillgänglighet
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'http://stackoverflow.com/questions/tagged/azure-container-service'
    - name: Videoklipp
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'