- name: Dokumentation om Azure Arc-aktiverad Kubernetes
  href: index.yml
- name: Översikt
  items:
    - name: Om Arc-aktiverat Kubernetes
      href: overview.md
- name: Anvisningar
  items:
    - name: Ansluta till Azure Arc
      items:
        - name: Anslut kluster
          href: connect-cluster.md
        - name: Huvudnamn för registreringstjänst
          href: create-onboarding-service-principal.md
    - name: Hantera
      items:
        - name: Distribuera konfigurationer med GitOps
          href: use-gitops-connected-cluster.md
        - name: Distribuera Helm-diagram med GitOps
          href: use-gitops-with-helm.md
        - name: Framtvinga GitOps med hjälp av Azure Policy
          href: use-azure-policy.md
        - name: Övervaka med hjälp av Azure Monitor för containrar
          href: ../../azure-monitor/insights/container-insights-enable-arc-enabled-clusters.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Principer för åtkomstkontroll med hjälp av Azure Policy
          href: ../../governance/policy/concepts/policy-for-kubernetes.md?toc=/azure/azure-arc/kubernetes/toc.yml
        - name: Distribuera IoT-arbetsbelastningar
          href: deploy-azure-iot-edge-workloads.md
    - name: Felsökning
      href: Troubleshooting.md
- name: Referens
  items:
    - name: Inbyggda Azure Policy-program
      displayName: 'samples, policies, definitions'
      href: policy-reference.md
    - name: Azure PowerShell
      href: /powershell/module/Az.ConnectedKubernetes/
- name: Resurser
  items:
    - name: Kom igång med Azure Arc
      href: 'https://github.com/microsoft/azure_arc'